
export default new Map([
    ['NA', { iso3: '', officialName: 'Undefined', rules: 'rules.json', isHybrid: false }],
    ['BG', { iso3: 'BUL', officialName: 'български (BG)', rules: 'rules.BG.json', isHybrid: false }],
    ['ES', { iso3: 'SPA', officialName: 'español (ES)', rules: 'rules.ES.json', isHybrid: false }],
    ['CS', { iso3: 'CES', officialName: 'čeština (CS)', rules: 'rules.CS.json', isHybrid: false }],
    ['DA', { iso3: 'DAN', officialName: 'dansk (DA)', rules: 'rules.DA.json', isHybrid: false }],
    ['DE', { iso3: 'DEU', officialName: 'Deutsch (DE)', rules: 'rules.DE.json', isHybrid: false }],
    ['ET', { iso3: 'EST', officialName: 'eesti (ET)', rules: 'rules.ET.json', isHybrid: false }],
    ['EL', { iso3: 'ELL', officialName: 'ελληνικά (EL)', rules: 'rules.EL.json', isHybrid: false }],
    ['EN', { iso3: 'ENG', officialName: 'English (EN)', rules: 'rules.EN.json', isHybrid: false }],
    ['FR', { iso3: 'FRA', officialName: 'français (FR)', rules: 'rules.FR.json', isHybrid: false }],
    ['GA', { iso3: 'GLE', officialName: 'Gaeilge (GA)', rules: 'rules.GA.json', isHybrid: false }],
    ['HR', { iso3: 'HRV', officialName: 'hrvatski (HR)', rules: 'rules.HR.json', isHybrid: false }],
    ['IT', { iso3: 'ITA', officialName: 'italiano (IT)', rules: 'rules.IT.json', isHybrid: false }],
    ['LV', { iso3: 'LAV', officialName: 'latviešu (LV)', rules: 'rules.LV.json', isHybrid: false }],
    ['LT', { iso3: 'LIT', officialName: 'lietuvių (LT)', rules: 'rules.LT.json', isHybrid: false }],
    ['HU', { iso3: 'HUN', officialName: 'magyar (HU)', rules: 'rules.HU.json', isHybrid: false }],
    ['MT', { iso3: 'MLT', officialName: 'Malti (MT)', rules: 'rules.MT.json', isHybrid: false }],
    ['NL', { iso3: 'NLD', officialName: 'Nederlands (NL)', rules: 'rules.NL.json', isHybrid: false }],
    ['PL', { iso3: 'POL', officialName: 'polski (PL)', rules: 'rules.PL.json', isHybrid: false }],
    ['PT', { iso3: 'POR', officialName: 'português (PT)', rules: 'rules.PT.json', isHybrid: false }],
    ['RO', { iso3: 'RON', officialName: 'română (RO)', rules: 'rules.RO.json', isHybrid: false }],
    ['SK', { iso3: 'SLK', officialName: 'slovenčina (SK)', rules: 'rules.SK.json', isHybrid: false }],
    ['SL', { iso3: 'SLV', officialName: 'slovenščina (SL)', rules: 'rules.SL.json', isHybrid: false }],
    ['FI', { iso3: 'FIN', officialName: 'suomi (FI)', rules: 'rules.FI.json', isHybrid: false }],
    ['SV', { iso3: 'SWE', officialName: 'svenska (SV)', rules: 'rules.SV.json', isHybrid: false }],
    ['ENDEFR', { iso3: 'ENDEFR', officialName: 'EN/FR/DE', rules: 'rules.ENDEFR.json', isHybrid: true }]
]);
